<?php
use Drupal\Core\Datetime\DateFormatterInterface;
/**
 * @file
 * buildinggreen theme file.
 */
function buildinggreen_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    $content_type = $node->bundle();
    $suggestions[] = 'page__'.$content_type;
  }
}
function buildinggreen_preprocess_node(&$variables) {
  $node = $variables['node'];
  //check content type
  if ($node->getType() == 'blog') {
    $variables['#attached']['library'][] = 'buildinggreen/blog';
  }
  // Obtenir le timestamp de création du contenu.
  $timestamp = $node->getCreatedTime();

  // Formater la date en "time ago".
  $date_formatter = \Drupal::service('date.formatter');
  $variables['time_ago'] = $date_formatter->formatTimeDiffSince($timestamp);
}


