<?php

/**
 * @file
 * buildinggreen theme file.
 */
function buildinggreen_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    $content_type = $node->bundle();
    $suggestions[] = 'page__'.$content_type;
  }
}
function buildinggreen_preprocess_node(&$variables) {
  $node = $variables['node'];
  //check content type
  if ($node->getType() == 'blog') {
    $variables['#attached']['library'][] = 'buildinggreen/blog';
  }
}
